name: run-tests-on-a-pull-request

on:
  pull_request:
    branches: [ main ]

jobs:
  call-tests-on-a-pull-request:
    uses: ./.github/workflows/run-tests-template.yml
    with:
      tags-of-tests-to-include: "smoke"
    secrets: inherit